CREATE TABLE MSD
    (ID NUMERIC,
    NAME VARCHAR(50),
    CONSTRAINT IMP_PK PRIMARY KEY (ID));

CREATE TABLE USERS_T
    (ID NUMERIC,
    NAME VARCHAR(50),
    CONSTRAINT USR_PK PRIMARY KEY (ID));

ALTER TABLE USERS_T
    ADD CONSTRAINT USERS_NAME UNIQUE (NAME);
    